chore: Add UI tests for Goals V2 page
operately/operately pull request #1418
Opened 2024-10-23 17:45 UTC by Rockyy174

I've added UI tests for the new Goals page.

2024-10-23 17:56 UTC, shiroyasha commented on test/features/goal_tree_test.exs
> +  defp visit_goals_v2_tmp(ctx) do
Move this to steps as well. In general let's aim to have most (all?) steps in the steps file.

2024-10-23 17:59 UTC, Rockyy174 commented on test/features/goal_tree_test.exs
> +  defp visit_goals_v2_tmp(ctx) do
Makes sense. Actually, I intend to delete this function as soon as we replace the goals page, so I didn't pay much attention to it. But I will move it to the steps file anyway.

2024-10-23 18:17 UTC, shiroyasha requested changes

2024-10-23 18:17 UTC, shiroyasha commented on test/features/goal_tree_test.exs
> +    |> Steps.refute_project_visible(:goal_2)
Feature tests give more value if they are written from the users's perspective, which in practice means using statements that describe the feature from the perspective of the user. Here is the main benefit: When someone else reads the steps, he should have a good understanding of the user interaction and the expection of the user.

In your example, you are focusing on what is happening, but it is not clear why.

```
ctx
|> visit_goals_v2_tmp()
|> Steps.assert_project_visible(:project_alpha)
|> Steps.assert_project_visible(:project_beta)
|> Steps.expand_collapse_node(id: Paths.goal_id(ctx.goal_1))
|> Steps.refute_project_visible(:project_alpha)
|> Steps.refute_project_visible(:project_beta)
|> Steps.expand_collapse_node(id: Paths.goal_id(ctx.goal_1))
|> Steps.assert_project_visible(:project_alpha)
|> Steps.assert_project_visible(:project_beta)
```

Here is an alternative that focuses on the user journey:

```
|> Step.given_the_user_is_a_company_member()
|> Step.when_the_user_visits_the_goalsv2_page()
|> Step.then_all_projects_are_visible_by_default()
|> Step.when_the_user_expands_a_goal()
|> Step.then_subgoals_and_projects_of_that_goal_should_be_visible()
```

There steps are using using [the given/when/then statements](https://martinfowler.com/bliki/GivenWhenThen.html) popular in many testing frameworks, especially in ones that are focusing on [BDD](https://cucumber.io/docs/bdd/). 

Using alternative kinds of steps (i.e. not being dogmatic about given/when/then) is also OK but we should aim to keep in on the high-level, and from the users perspective.

For example:

```
|> Step.given_iam_a_company_member()
|> Step.visit_the_goalsv2_page()
|> Step.assert_all_projects_are_visible_by_default()
|> Step.expands_a_goal()
|> Step.assert_that_subgoals_and_projects_of_that_goal_are_visible()
```

2024-10-23 18:17 UTC, shiroyasha commented on test/support/features/goal_tree_steps.ex
> +    testid = "toggle-node-" <> id |> String.downcase()
There is a helper: `UI.testid(...)` that can help with this.

2024-10-23 18:21 UTC, Rockyy174 commented on test/features/goal_tree_test.exs
> +    |> Steps.refute_project_visible(:goal_2)
Got it. I will make sure to update the step names.

2024-10-24 08:08 UTC, shiroyasha commented on test/features/goal_tree_test.exs
> +    |> Steps.refute_project_visible(:goal_2)
Nice changes, the new ones are much better. The only thing that remains is the `filter goals and projects` feature. It is quite intimidating block of tests. Can you brake it down into smaller features so that it is more manageable?

2024-10-24 13:33 UTC, merged